# Generated by Django 4.0.4 on 2022-05-29 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_alter_player_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='trophies',
            field=models.TextField(blank=True),
        ),
    ]
