# Generated by Django 4.0.4 on 2022-05-29 23:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0003_alter_player_trophies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='shirt_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
