# Generated by Django 4.0.4 on 2022-05-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0005_alter_player_shirt_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='full_name',
        ),
        migrations.AddField(
            model_name='player',
            name='short_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
