# Generated by Django 4.0.4 on 2022-05-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0006_rename_name_player_full_name_player_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.CharField(default='John Doe', max_length=10),
        ),
    ]
