# Generated by Django 4.0.4 on 2022-05-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0008_alter_player_short_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='short_name',
            field=models.CharField(max_length=11),
        ),
    ]
