# Generated by Django 4.0.4 on 2022-06-01 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0009_alter_player_short_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='profile_pic',
            new_name='list_pic',
        ),
        migrations.AddField(
            model_name='player',
            name='details_pic',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
