# Generated by Django 4.0.4 on 2022-06-02 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0010_rename_profile_pic_player_list_pic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='debut',
        ),
        migrations.RemoveField(
            model_name='player',
            name='trophies',
        ),
        migrations.AddField(
            model_name='player',
            name='facebook_link',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='instagram_link',
            field=models.URLField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='player',
            name='player_bio',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='player',
            name='twitter_link',
            field=models.URLField(default='', max_length=100),
        ),
    ]
