# Generated by Django 4.0.4 on 2022-06-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0011_remove_player_debut_remove_player_trophies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='facebook_link',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='instagram_link',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='player_bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='player',
            name='twitter_link',
            field=models.URLField(blank=True, default='', max_length=100),
        ),
    ]
