# Generated by Django 4.0.4 on 2022-06-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0012_alter_player_facebook_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='bio_headline',
            field=models.CharField(default='', max_length=200),
        ),
    ]
