# Generated by Django 4.0.4 on 2022-06-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0013_player_bio_headline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='bio_headline',
            field=models.CharField(max_length=200),
        ),
    ]
