# Generated by Django 4.0.4 on 2022-06-10 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0017_alter_comment_commenter_alter_comment_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='admin_name',
            new_name='added_by',
        ),
    ]
