# Generated by Django 4.0.4 on 2022-06-10 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0018_rename_admin_name_player_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='added_by',
            field=models.ForeignKey(default=None, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
