# Generated by Django 4.0.4 on 2022-06-10 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0020_comment_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='players.player'),
        ),
    ]
