# Generated by Django 4.0.4 on 2022-06-10 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0021_alter_comment_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commenter',
            new_name='posted_by',
        ),
    ]
