# Generated by Django 4.0.4 on 2022-06-11 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0022_rename_commenter_comment_posted_by'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
