# Generated by Django 4.0.4 on 2022-06-11 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0024_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
