# Generated by Django 4.0.4 on 2022-06-11 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0027_alter_comment_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title',
            new_name='header',
        ),
    ]
