# Generated by Django 4.0.4 on 2022-06-12 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('players', '0028_rename_title_comment_header'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='added_by',
            field=models.ForeignKey(default=None, limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL),
        ),
    ]
